# Generated by Django 5.1.2 on 2025-09-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('rollNumber', models.CharField(max_length=20)),
                ('roomNumber', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dueDate', models.DateField()),
                ('paidDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('paymentMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('transactionId', models.CharField(blank=True, max_length=100, null=True)),
                ('lateFee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lastMaintenance', models.DateField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollNumber', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('roomNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('joinDate', models.DateField()),
                ('feeStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
